services:
  traefik:
    image: traefik:latest
    command:
      - "--api"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--providers.docker.swarmMode=true"

      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=ne_bknn@sprush.rocks"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "./letsencrypt:/letsencrypt"
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    networks:
      - traefik-net
    deploy:
      placement:
        constraints:
          - node.role==manager

networks:
  traefik-net:
    driver: overlay
    attachable: true