---
- name: Install python3-docker
  ansible.builtin.apt:
    name: python3-docker
    state: present
    update_cache: true
  become: true

- name: Init swarm on the first node
  community.general.docker_swarm:
    state: present
    advertise_addr: "{{ ansible_default_ipv4.address }}"
    labels:
      status: master
  register: result
  when: inventory_hostname == 'server-0'

- name: Get join-token for worker nodes
  ansible.builtin.set_fact:
    join_token_worker: "{{ hostvars['server-0'].result.swarm_facts.JoinTokens.Worker }}"

- name: Join workers
  community.general.docker_swarm:
    state: join
    join_token: "{{ join_token_worker }}"
    advertise_addr: "{{ ansible_default_ipv4.address }}"
    remote_addrs: "{{ hostvars['server-0'].ansible_default_ipv4.address }}"
    labels:
      status: worker
  when:
    - inventory_hostname != 'server-0'
